In [152]:
import numpy as np
import pandas as pd

data = './datasets/Kangaroo.csv'
data_set = pd.read_csv(data, sep = ',')
df = pd.DataFrame(data_set)

print(df)

       Unnamed: 0          id  \
0               0  20661494.0
1               1  20647642.0
2               2  20644816.0
3               3  20659813.0
4               4  20633249.0
...           ...         ...
80363      440319  20663057.0
80364      440364  20664347.0
80365      440966  20664354.0
80366      442237  20664377.0
80367      446550  20664387.0

                                                     url       type  \
0      https://www.immoweb.be/en/classified/apartment...  APARTMENT
1      https://www.immoweb.be/en/classified/house/for...      HOUSE
2      https://www.immoweb.be/en/classified/apartment...  APARTMENT
3      https://www.immoweb.be/en/classified/apartment...  APARTMENT
4      https://www.immoweb.be/en/classified/flat-stud...  APARTMENT
...                                                  ...        ...
80363  https://www.immoweb.be/en/classified/villa/for...      HOUSE
80364  https://www.immoweb.be/en/classified/apartment...  APARTMENT
80365  https://www.immoweb.be/en/classified/apartment...  APARTMENT
80366  https://www.immoweb.be/en/classified/apartment...  APARTMENT
80367  https://www.immoweb.be/en/classified/apartment...  APARTMENT

           subtype  bedroomCount  bathroomCount         province  \
0        APARTMENT           2.0            1.0         Brussels
1            HOUSE           4.0            2.0         Brussels
2        APARTMENT           2.0            1.0         Brussels
3        APARTMENT           2.0            2.0         Brussels
4      FLAT_STUDIO           1.0            1.0         Brussels
...            ...           ...            ...              ...
80363        VILLA           3.0            1.0          Antwerp
80364    APARTMENT           3.0            1.0         Brussels
80365    APARTMENT           3.0            1.0  Flemish Brabant
80366    APARTMENT           3.0            2.0    West Flanders
80367    APARTMENT           3.0            2.0          Antwerp

                         locality  postCode  ...  hasOffice  toiletCount  \
0                       Etterbeek      1040  ...        NaN          1.0
1                       Etterbeek      1040  ...       True          3.0
2                       Etterbeek      1040  ...        NaN          1.0
3                       Bruxelles      1040  ...        NaN          2.0
4                       Etterbeek      1040  ...        NaN          1.0
...                           ...       ...  ...        ...          ...
80363                  Willebroek      2830  ...        NaN          3.0
80364                       Jette      1090  ...        NaN          1.0
80365  Grimbergen Strombeek-Bever      1853  ...        NaN          1.0
80366                    Westende      8434  ...        NaN          2.0
80367                     Wilrijk      2610  ...        NaN          2.0

       hasSwimmingPool hasFireplace hasTerrace terraceSurface  \
0                  NaN          NaN       True            7.0
1                  NaN          NaN       True            1.0
2                  NaN          NaN       True            2.0
3                  NaN          NaN       True            3.0
4                  NaN          NaN        NaN            NaN
...                ...          ...        ...            ...
80363             True          NaN       True            NaN
80364              NaN          NaN       True           10.0
80365              NaN          NaN       True            9.0
80366              NaN          NaN       True            NaN
80367              NaN          NaN       True            NaN

       terraceOrientation accessibleDisabledPeople epcScore     price
0                     NaN                      NaN        C  399000.0
1                     NaN                      NaN        E  895000.0
2                     NaN                      NaN        F  465000.0
3                     NaN                      NaN        B  590000.0
4                     NaN                      NaN        E  289000.0
...                   ...                      ...      ...       ...
80363                 NaN                      NaN        B  849000.0
80364                 NaN                      NaN        D  279000.0
80365                 NaN                      NaN        B  299000.0
80366                 NaN                      NaN        A  325000.0
80367                 NaN                      NaN        B  340000.0

[80368 rows x 53 columns]

In [153]:
na_values = df.isnull().sum()
missing_percent = (na_values/ len(df)) * 100
print (missing_percent.round(2))

Unnamed: 0                    0.00
id                            0.00
url                           0.00
type                          0.00
subtype                       0.00
bedroomCount                  8.47
bathroomCount                17.04
province                      0.00
locality                      0.00
postCode                      0.00
habitableSurface             15.66
roomCount                    72.69
monthlyCost                 100.00
hasAttic                     84.43
hasBasement                  63.52
hasDressingRoom              96.73
diningRoomSurface            91.41
hasDiningRoom                82.40
buildingCondition            27.84
buildingConstructionYear     38.90
facedeCount                  33.76
floorCount                   53.28
streetFacadeWidth            80.70
hasLift                      76.30
floodZoneType                44.67
heatingType                  41.33
hasHeatPump                  90.70
hasPhotovoltaicPanels        89.99
hasThermicPanels             96.13
kitchenSurface               69.81
kitchenType                  47.84
landSurface                  50.80
hasLivingRoom                46.65
livingRoomSurface            63.98
hasBalcony                  100.00
hasGarden                    80.14
gardenSurface                80.14
gardenOrientation            93.03
parkingCountIndoor           64.86
parkingCountOutdoor          77.20
hasAirConditioning           98.60
hasArmoredDoor               95.40
hasVisiophone                80.10
hasOffice                    87.08
toiletCount                  31.45
hasSwimmingPool              97.74
hasFireplace                 96.21
hasTerrace                   40.99
terraceSurface               64.41
terraceOrientation           85.99
accessibleDisabledPeople    100.00
epcScore                     18.64
price                         4.97
dtype: float64

Step 1 : Data Cleaning

In [154]:
# Remove non relevant columns
df= data_set.drop(columns=['url','monthlyCost','accessibleDisabledPeople','gardenOrientation','terraceOrientation'])
print(df)

       Unnamed: 0          id       type      subtype  bedroomCount  \
0               0  20661494.0  APARTMENT    APARTMENT           2.0
1               1  20647642.0      HOUSE        HOUSE           4.0
2               2  20644816.0  APARTMENT    APARTMENT           2.0
3               3  20659813.0  APARTMENT    APARTMENT           2.0
4               4  20633249.0  APARTMENT  FLAT_STUDIO           1.0
...           ...         ...        ...          ...           ...
80363      440319  20663057.0      HOUSE        VILLA           3.0
80364      440364  20664347.0  APARTMENT    APARTMENT           3.0
80365      440966  20664354.0  APARTMENT    APARTMENT           3.0
80366      442237  20664377.0  APARTMENT    APARTMENT           3.0
80367      446550  20664387.0  APARTMENT    APARTMENT           3.0

       bathroomCount         province                    locality  postCode  \
0                1.0         Brussels                   Etterbeek      1040
1                2.0         Brussels                   Etterbeek      1040
2                1.0         Brussels                   Etterbeek      1040
3                2.0         Brussels                   Bruxelles      1040
4                1.0         Brussels                   Etterbeek      1040
...              ...              ...                         ...       ...
80363            1.0          Antwerp                  Willebroek      2830
80364            1.0         Brussels                       Jette      1090
80365            1.0  Flemish Brabant  Grimbergen Strombeek-Bever      1853
80366            2.0    West Flanders                    Westende      8434
80367            2.0          Antwerp                     Wilrijk      2610

       habitableSurface  ...  hasArmoredDoor hasVisiophone hasOffice  \
0                 100.0  ...             NaN          True       NaN
1                 270.0  ...             NaN           NaN      True
2                  87.0  ...             NaN           NaN       NaN
3                 104.0  ...            True          True       NaN
4                  71.0  ...             NaN           NaN       NaN
...                 ...  ...             ...           ...       ...
80363             252.0  ...            True          True       NaN
80364              94.0  ...             NaN          True       NaN
80365             113.0  ...             NaN           NaN       NaN
80366             111.0  ...             NaN           NaN       NaN
80367             132.0  ...             NaN          True       NaN

      toiletCount  hasSwimmingPool hasFireplace hasTerrace  terraceSurface  \
0             1.0              NaN          NaN       True             7.0
1             3.0              NaN          NaN       True             1.0
2             1.0              NaN          NaN       True             2.0
3             2.0              NaN          NaN       True             3.0
4             1.0              NaN          NaN        NaN             NaN
...           ...              ...          ...        ...             ...
80363         3.0             True          NaN       True             NaN
80364         1.0              NaN          NaN       True            10.0
80365         1.0              NaN          NaN       True             9.0
80366         2.0              NaN          NaN       True             NaN
80367         2.0              NaN          NaN       True             NaN

       epcScore     price
0             C  399000.0
1             E  895000.0
2             F  465000.0
3             B  590000.0
4             E  289000.0
...         ...       ...
80363         B  849000.0
80364         D  279000.0
80365         B  299000.0
80366         A  325000.0
80367         B  340000.0

[80368 rows x 48 columns]

In [155]:
duplicates = data_set.duplicated()
print(duplicates.count)

<bound method Series.count of 0        False
1        False
2        False
3        False
4        False
         ...
80363    False
80364    False
80365    False
80366    False
80367    False
Length: 80368, dtype: bool>

In [156]:
#Replace Missing_value to "0"
df = df.fillna(0)
print(df)

       Unnamed: 0          id       type      subtype  bedroomCount  \
0               0  20661494.0  APARTMENT    APARTMENT           2.0
1               1  20647642.0      HOUSE        HOUSE           4.0
2               2  20644816.0  APARTMENT    APARTMENT           2.0
3               3  20659813.0  APARTMENT    APARTMENT           2.0
4               4  20633249.0  APARTMENT  FLAT_STUDIO           1.0
...           ...         ...        ...          ...           ...
80363      440319  20663057.0      HOUSE        VILLA           3.0
80364      440364  20664347.0  APARTMENT    APARTMENT           3.0
80365      440966  20664354.0  APARTMENT    APARTMENT           3.0
80366      442237  20664377.0  APARTMENT    APARTMENT           3.0
80367      446550  20664387.0  APARTMENT    APARTMENT           3.0

       bathroomCount         province                    locality  postCode  \
0                1.0         Brussels                   Etterbeek      1040
1                2.0         Brussels                   Etterbeek      1040
2                1.0         Brussels                   Etterbeek      1040
3                2.0         Brussels                   Bruxelles      1040
4                1.0         Brussels                   Etterbeek      1040
...              ...              ...                         ...       ...
80363            1.0          Antwerp                  Willebroek      2830
80364            1.0         Brussels                       Jette      1090
80365            1.0  Flemish Brabant  Grimbergen Strombeek-Bever      1853
80366            2.0    West Flanders                    Westende      8434
80367            2.0          Antwerp                     Wilrijk      2610

       habitableSurface  ...  hasArmoredDoor hasVisiophone hasOffice  \
0                 100.0  ...               0          True         0
1                 270.0  ...               0             0      True
2                  87.0  ...               0             0         0
3                 104.0  ...            True          True         0
4                  71.0  ...               0             0         0
...                 ...  ...             ...           ...       ...
80363             252.0  ...            True          True         0
80364              94.0  ...               0          True         0
80365             113.0  ...               0             0         0
80366             111.0  ...               0             0         0
80367             132.0  ...               0          True         0

      toiletCount  hasSwimmingPool hasFireplace hasTerrace  terraceSurface  \
0             1.0                0            0       True             7.0
1             3.0                0            0       True             1.0
2             1.0                0            0       True             2.0
3             2.0                0            0       True             3.0
4             1.0                0            0          0             0.0
...           ...              ...          ...        ...             ...
80363         3.0             True            0       True             0.0
80364         1.0                0            0       True            10.0
80365         1.0                0            0       True             9.0
80366         2.0                0            0       True             0.0
80367         2.0                0            0       True             0.0

       epcScore     price
0             C  399000.0
1             E  895000.0
2             F  465000.0
3             B  590000.0
4             E  289000.0
...         ...       ...
80363         B  849000.0
80364         D  279000.0
80365         B  299000.0
80366         A  325000.0
80367         B  340000.0

[80368 rows x 48 columns]

In [157]:
#Replace "True" by 1
df = df.replace(True, 1)
print(df)

       Unnamed: 0          id       type      subtype  bedroomCount  \
0               0  20661494.0  APARTMENT    APARTMENT           2.0
1               1  20647642.0      HOUSE        HOUSE           4.0
2               2  20644816.0  APARTMENT    APARTMENT           2.0
3               3  20659813.0  APARTMENT    APARTMENT           2.0
4               4  20633249.0  APARTMENT  FLAT_STUDIO           1.0
...           ...         ...        ...          ...           ...
80363      440319  20663057.0      HOUSE        VILLA           3.0
80364      440364  20664347.0  APARTMENT    APARTMENT           3.0
80365      440966  20664354.0  APARTMENT    APARTMENT           3.0
80366      442237  20664377.0  APARTMENT    APARTMENT           3.0
80367      446550  20664387.0  APARTMENT    APARTMENT           3.0

       bathroomCount         province                    locality  postCode  \
0                1.0         Brussels                   Etterbeek      1040
1                2.0         Brussels                   Etterbeek      1040
2                1.0         Brussels                   Etterbeek      1040
3                2.0         Brussels                   Bruxelles      1040
4                1.0         Brussels                   Etterbeek      1040
...              ...              ...                         ...       ...
80363            1.0          Antwerp                  Willebroek      2830
80364            1.0         Brussels                       Jette      1090
80365            1.0  Flemish Brabant  Grimbergen Strombeek-Bever      1853
80366            2.0    West Flanders                    Westende      8434
80367            2.0          Antwerp                     Wilrijk      2610

       habitableSurface  ...  hasArmoredDoor  hasVisiophone  hasOffice  \
0                 100.0  ...               0              1          0
1                 270.0  ...               0              0          1
2                  87.0  ...               0              0          0
3                 104.0  ...               1              1          0
4                  71.0  ...               0              0          0
...                 ...  ...             ...            ...        ...
80363             252.0  ...               1              1          0
80364              94.0  ...               0              1          0
80365             113.0  ...               0              0          0
80366             111.0  ...               0              0          0
80367             132.0  ...               0              1          0

       toiletCount  hasSwimmingPool  hasFireplace hasTerrace  terraceSurface  \
0              1.0                0             0          1             7.0
1              3.0                0             0          1             1.0
2              1.0                0             0          1             2.0
3              2.0                0             0          1             3.0
4              1.0                0             0          0             0.0
...            ...              ...           ...        ...             ...
80363          3.0                1             0          1             0.0
80364          1.0                0             0          1            10.0
80365          1.0                0             0          1             9.0
80366          2.0                0             0          1             0.0
80367          2.0                0             0          1             0.0

       epcScore     price
0             C  399000.0
1             E  895000.0
2             F  465000.0
3             B  590000.0
4             E  289000.0
...         ...       ...
80363         B  849000.0
80364         D  279000.0
80365         B  299000.0
80366         A  325000.0
80367         B  340000.0

[80368 rows x 48 columns]

C:\Users\nattt\AppData\Local\Temp\ipykernel_1536\1717690634.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace(True, 1)

In [158]:
# Delete row when the price == 0
df = df[df['price'] != 0]
print(df)

       Unnamed: 0          id       type      subtype  bedroomCount  \
0               0  20661494.0  APARTMENT    APARTMENT           2.0
1               1  20647642.0      HOUSE        HOUSE           4.0
2               2  20644816.0  APARTMENT    APARTMENT           2.0
3               3  20659813.0  APARTMENT    APARTMENT           2.0
4               4  20633249.0  APARTMENT  FLAT_STUDIO           1.0
...           ...         ...        ...          ...           ...
80363      440319  20663057.0      HOUSE        VILLA           3.0
80364      440364  20664347.0  APARTMENT    APARTMENT           3.0
80365      440966  20664354.0  APARTMENT    APARTMENT           3.0
80366      442237  20664377.0  APARTMENT    APARTMENT           3.0
80367      446550  20664387.0  APARTMENT    APARTMENT           3.0

       bathroomCount         province                    locality  postCode  \
0                1.0         Brussels                   Etterbeek      1040
1                2.0         Brussels                   Etterbeek      1040
2                1.0         Brussels                   Etterbeek      1040
3                2.0         Brussels                   Bruxelles      1040
4                1.0         Brussels                   Etterbeek      1040
...              ...              ...                         ...       ...
80363            1.0          Antwerp                  Willebroek      2830
80364            1.0         Brussels                       Jette      1090
80365            1.0  Flemish Brabant  Grimbergen Strombeek-Bever      1853
80366            2.0    West Flanders                    Westende      8434
80367            2.0          Antwerp                     Wilrijk      2610

       habitableSurface  ...  hasArmoredDoor  hasVisiophone  hasOffice  \
0                 100.0  ...               0              1          0
1                 270.0  ...               0              0          1
2                  87.0  ...               0              0          0
3                 104.0  ...               1              1          0
4                  71.0  ...               0              0          0
...                 ...  ...             ...            ...        ...
80363             252.0  ...               1              1          0
80364              94.0  ...               0              1          0
80365             113.0  ...               0              0          0
80366             111.0  ...               0              0          0
80367             132.0  ...               0              1          0

       toiletCount  hasSwimmingPool  hasFireplace hasTerrace  terraceSurface  \
0              1.0                0             0          1             7.0
1              3.0                0             0          1             1.0
2              1.0                0             0          1             2.0
3              2.0                0             0          1             3.0
4              1.0                0             0          0             0.0
...            ...              ...           ...        ...             ...
80363          3.0                1             0          1             0.0
80364          1.0                0             0          1            10.0
80365          1.0                0             0          1             9.0
80366          2.0                0             0          1             0.0
80367          2.0                0             0          1             0.0

       epcScore     price
0             C  399000.0
1             E  895000.0
2             F  465000.0
3             B  590000.0
4             E  289000.0
...         ...       ...
80363         B  849000.0
80364         D  279000.0
80365         B  299000.0
80366         A  325000.0
80367         B  340000.0

[76370 rows x 48 columns]

In [159]:
df.to_csv("my_clean_data.csv", index=False, encoding='utf-8')